"""Agent registry — publishing, versioning and discovering the agents in this system.

An enterprise cannot approve what it cannot enumerate. The registry emits a card per
agent describing what it is, what model it runs, what it is allowed to touch, and — the
part that matters for compliance — exactly which fields of an entity are permitted to
reach a model.

Versions are content-derived, not hand-maintained. An agent's version is a hash of the
things that change its behaviour: its instruction, its generation settings, and the tools
it can call. Edit a prompt and the version moves on its own; rename a variable and it does
not. A hand-incremented version number is a promise someone eventually forgets to keep.

Every tool on a card carries its reversibility class, so an approver can see at a glance
which agents can move money or send mail, and which can only read.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from kernel.effect import Determinism, digest, hash_payload


@dataclass(frozen=True, slots=True)
class ToolCard:
    name: str
    reversibility: str
    reads: tuple[str, ...] = ()
    compensating: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "reversibility": self.reversibility,
            "reads": list(self.reads),
            "has_compensator": self.compensating,
        }


@dataclass(frozen=True, slots=True)
class AgentCard:
    """One published, versioned, discoverable agent."""

    id: str
    role: str
    summary: str
    model: str
    thinking_level: str
    temperature: float
    tools: tuple[ToolCard, ...] = ()
    # The only fields of an entity this agent's reasoning is allowed to see. Empty means
    # the agent receives conversation context rather than a projected entity.
    sees: tuple[str, ...] = ()
    # Fields explicitly withheld. Stated rather than implied, because "we don't send PII"
    # is only checkable if someone wrote down what PII means here.
    never_sees: tuple[str, ...] = ()
    delegates_to: tuple[str, ...] = ()
    instruction: str = ""
    status: str = "approved"

    @property
    def version(self) -> str:
        """Content-derived: changes exactly when behaviour changes.

        The role is included because it is not merely a label — `Effect.address` hashes
        the agent name into every model and tool call, so two agents with identical
        configuration but different roles genuinely address differently and do not share
        each other's work. Leaving it out made two distinctly-behaving agents publish the
        same version.
        """
        return digest(
            self.role,
            self.instruction,
            self.model,
            self.thinking_level,
            str(self.temperature),
            hash_payload(sorted(t.name for t in self.tools)),
            hash_payload(sorted(self.sees)),
        )[:12]

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "version": self.version,
            "role": self.role,
            "summary": self.summary,
            "status": self.status,
            "model": self.model,
            "generation": {
                "thinking_level": self.thinking_level,
                "temperature": self.temperature,
            },
            "tools": [t.to_dict() for t in self.tools],
            "data_policy": {
                "sees": list(self.sees),
                "never_sees": list(self.never_sees),
            },
            "delegates_to": list(self.delegates_to),
        }


# -- the published catalogue --------------------------------------------------

# Kept beside the agents themselves rather than generated by introspection: a registry
# that derives everything from code can only ever restate what the code does, and cannot
# record what an approver was told the agent would do. The version hash is what keeps the
# two honest — if the instruction drifts from the card, the version moves.

# Exactly the keys Projection.to_dict emits, so tests/test_registry.py can assert the
# card and the projection agree rather than approximately agree.
PASSENGER_SEES = ("role", "tier", "urgency", "party", "constraints",
                  "haul", "hotel_entitled", "misconnect")
PASSENGER_NEVER_SEES = (
    "name", "passenger_id", "email", "order_id", "destination",
    "original_flight", "scheduled_departure",
)

SWARM_AGENTS = (
    AgentCard(
        id="chorus.passenger",
        role="passenger",
        summary=(
            "Represents one stranded traveller. Reasons only about a bucketed projection "
            "of its situation, so agents in equivalent positions share a single thought."
        ),
        model="gemini-3.5-flash",
        thinking_level="low",
        temperature=0.0,
        sees=PASSENGER_SEES,
        never_sees=PASSENGER_NEVER_SEES,
    ),
    AgentCard(
        id="chorus.crew",
        role="crew",
        summary=(
            "Represents one crew member. Reasons about duty legality and base position; "
            "duty limits are law, not preference."
        ),
        model="gemini-3.5-flash",
        thinking_level="low",
        temperature=0.0,
        sees=("role", "tier", "urgency", "party", "constraints",
              "haul", "hotel_entitled", "misconnect"),
        never_sees=("name", "crew_id", "employee_number"),
    ),
)


def build_registry() -> dict[str, Any]:
    """The full catalogue, including the dispute fleet if its tools can be constructed."""
    cards: list[AgentCard] = list(SWARM_AGENTS)
    cards.extend(_dispute_fleet_cards())
    return {
        "registry": "chorus",
        "count": len(cards),
        "agents": [c.to_dict() for c in cards],
        "reversibility_classes": {
            d.value: (
                "replayed from the record, never re-executed"
                if d in (Determinism.PURE, Determinism.RECORDED)
                else "re-executed against branch state, compensator retained"
                if d is Determinism.EXTERNAL_REVERSIBLE
                else "never dispatched off production; recorded as a counterfactual"
            )
            for d in Determinism
        },
    }


def _dispute_fleet_cards() -> list[AgentCard]:
    """Cards for the six-agent dispute fleet, with tool classes read from the registry
    that actually gates them at runtime — so the card cannot claim a tool is safer than
    the quarantine gate treats it."""
    from fleet.tools import FleetContext, build_tools
    from kernel.branch import PRIMARY
    from world.shadow import ShadowWorld

    _, reg = build_tools(FleetContext(world=ShadowWorld(), branch_id=PRIMARY))

    def cards_for(names: tuple[str, ...]) -> tuple[ToolCard, ...]:
        return tuple(
            ToolCard(
                name=n,
                reversibility=reg.classify(n).value,
                reads=reg.reads_of(n),
                compensating=bool(reg.get(n) and reg.get(n).compensator),
            )
            for n in names
        )

    spec = [
        ("fleet.triage", "triage", "low",
         "Loads the dispute and the customer, and states the facts in five lines.",
         ("get_dispute", "get_customer"), ()),
        ("fleet.policy", "policy", "high",
         "Retrieves the controlling policy clauses and decides approve or escalate. The "
         "one decision in the fleet that moves money, so it gets the largest budget.",
         ("search_policy",), ()),
        ("fleet.resolver", "resolver", "low",
         "Routes a decided dispute to the specialist that executes it.",
         (), ("fleet.refund_specialist", "fleet.escalation_specialist")),
        ("fleet.refund_specialist", "refund_specialist", "low",
         "Executes approved refunds and writes the ledger entry.",
         ("issue_refund", "record_ledger_entry", "set_dispute_status"), ()),
        ("fleet.escalation_specialist", "escalation_specialist", "low",
         "Routes disputes needing human judgement into a reviewer's queue.",
         ("escalate_to_human", "set_dispute_status"), ()),
        ("fleet.comms", "comms", "low",
         "Notifies the customer exactly once, redacting identifiers for EU residents.",
         ("send_customer_email",), ()),
    ]

    return [
        AgentCard(
            id=aid, role=role, summary=summary, model="gemini-3.5-flash",
            thinking_level=thinking, temperature=0.1,
            tools=cards_for(tools), delegates_to=delegates,
        )
        for aid, role, thinking, summary, tools, delegates in spec
    ]
